/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phonebook;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;



public class PhonebookApp extends javax.swing.JFrame implements CRUD_Interface{
    public DefaultListModel model = new DefaultListModel<>();
    /**
     * Creates new form PhonebookApp
     */
    public PhonebookApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEntryDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FirstNameInput = new javax.swing.JTextField();
        NumberInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        AddressInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        AddEntryBackButton = new javax.swing.JButton();
        BirthMonthInput = new javax.swing.JTextField();
        BirthYearInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LastNameInput = new javax.swing.JTextField();
        BirthDayInput = new javax.swing.JTextField();
        UpdateEntryDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        FirstNameTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        NumberTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BirthDayTextField = new javax.swing.JTextField();
        BirthMonthTextField = new javax.swing.JTextField();
        BirthYearTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        SearchDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LastNameOutput = new javax.swing.JLabel();
        FirstNameOutput = new javax.swing.JLabel();
        BirthdayOutput = new javax.swing.JLabel();
        NumberOutput = new javax.swing.JLabel();
        AddressOutput = new javax.swing.JLabel();
        EmailOutput = new javax.swing.JLabel();
        DeleteEntry = new javax.swing.JButton();
        UpdateEntry = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(model);
        jLabel25 = new javax.swing.JLabel();
        AddEntry = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();

        AddEntryDialog.setMinimumSize(new java.awt.Dimension(270, 395));

        jPanel5.setBackground(new java.awt.Color(43, 122, 120));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Input New Entry");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("First Name:");

        SubmitButton.setBackground(new java.awt.Color(0, 102, 102));
        SubmitButton.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(204, 204, 204));
        SubmitButton.setText("Submit");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        AddEntryBackButton.setBackground(new java.awt.Color(0, 102, 102));
        AddEntryBackButton.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        AddEntryBackButton.setForeground(new java.awt.Color(204, 204, 204));
        AddEntryBackButton.setText("Back");
        AddEntryBackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddEntryBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryBackButtonActionPerformed(evt);
            }
        });

        BirthMonthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthInputActionPerformed(evt);
            }
        });
        BirthMonthInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthInput,2);
            }
        });

        BirthYearInput.setToolTipText("");
        BirthYearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthYearInputActionPerformed(evt);
            }
        });
        BirthYearInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearInput,4);
            }
        });

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Last Name:");

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Birthday (mm/dd/yyyy):");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Number:");

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Address:");

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Email:");

        LastNameInput.setToolTipText("");
        LastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameInputActionPerformed(evt);
            }
        });

        BirthDayInput.setToolTipText("");
        BirthDayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayInputActionPerformed(evt);
            }
        });
        BirthDayInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayInput,2);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(AddEntryBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SubmitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(NumberInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddressInput, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 34, Short.MAX_VALUE))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BirthDayInput, BirthMonthInput, BirthYearInput});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEntryBackButton)
                    .addComponent(SubmitButton))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        NumberInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberInput,11);
            }
        });
        SubmitButton.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                String fullDate = BirthDayInput.getText()+"/"+BirthMonthInput.getText()+"/"+BirthYearInput.getText();
                if (FirstNameInput.getText().isEmpty()||LastNameInput.getText().isEmpty()||BirthDayInput.getText().isEmpty()||AddressInput.getText().isEmpty()||EmailInput.getText().isEmpty()||NumberInput.getText().isEmpty()){

                    System.out.println("Please input complete and correct information");
                    JOptionPane.showMessageDialog(AddEntryDialog,"Please input complete and correct information","Error",JOptionPane.ERROR_MESSAGE);
                } else{
                    CRUD_Interface.addRow(FirstNameInput.getText(), LastNameInput.getText(), fullDate, AddressInput.getText(), EmailInput.getText(), NumberInput.getText());
                    int index = (model.isEmpty())? 0:indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText()));
                    model.add(index, FirstNameInput.getText());
                    System.out.println(indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText())));
                    AddEntryDialog.dispose();
                }
            }
        });

        javax.swing.GroupLayout AddEntryDialogLayout = new javax.swing.GroupLayout(AddEntryDialog.getContentPane());
        AddEntryDialog.getContentPane().setLayout(AddEntryDialogLayout);
        AddEntryDialogLayout.setHorizontalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddEntryDialogLayout.setVerticalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEntryDialogLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        UpdateEntryDialog.setBackground(new java.awt.Color(43, 122, 120));
        UpdateEntryDialog.setMinimumSize(new java.awt.Dimension(285, 375));
        UpdateEntryDialog.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(43, 122, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(260, 378));

        FirstNameTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        FirstNameTextField.setForeground(new java.awt.Color(102, 102, 102));
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("First Name:");

        jLabel19.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Edit");

        jLabel17.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Last Name:");

        LastNameTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        LastNameTextField.setForeground(new java.awt.Color(102, 102, 102));
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Number:");

        NumberTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        NumberTextField.setForeground(new java.awt.Color(102, 102, 102));
        NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Address:");

        AddressTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        AddressTextField.setForeground(new java.awt.Color(102, 102, 102));
        AddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextFieldActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Email:");

        EmailTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        EmailTextField.setForeground(new java.awt.Color(102, 102, 102));
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Birthday (mm/dd/yyyy):");

        BirthDayTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        BirthDayTextField.setName(""); // NOI18N
        BirthDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayTextFieldActionPerformed(evt);
            }
        });
        BirthDayTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayTextField,2);
            }
        });

        BirthMonthTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        BirthMonthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthTextFieldActionPerformed(evt);
            }
        });

        BirthYearTextField.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Discard");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(0, 102, 102));
        UpdateButton.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(204, 204, 204));
        UpdateButton.setText("Save");
        UpdateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16)
                                .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(BirthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(BirthMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(BirthYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BirthDayTextField, BirthMonthTextField, BirthYearTextField});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddressTextField, EmailTextField, FirstNameTextField, LastNameTextField, NumberTextField});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BirthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(UpdateButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        NumberTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberTextField,11);
            }
        });
        BirthMonthTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthTextField,2);
            }
        });
        BirthYearTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearTextField,4);
            }
        });

        javax.swing.GroupLayout UpdateEntryDialogLayout = new javax.swing.GroupLayout(UpdateEntryDialog.getContentPane());
        UpdateEntryDialog.getContentPane().setLayout(UpdateEntryDialogLayout);
        UpdateEntryDialogLayout.setHorizontalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateEntryDialogLayout.setVerticalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SearchDialogLayout = new javax.swing.GroupLayout(SearchDialog.getContentPane());
        SearchDialog.getContentPane().setLayout(SearchDialogLayout);
        SearchDialogLayout.setHorizontalGroup(
            SearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SearchDialogLayout.setVerticalGroup(
            SearchDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setMinimumSize(new java.awt.Dimension(450, 300));

        jPanel2.setBackground(new java.awt.Color(43, 122, 120));

        jPanel1.setBackground(new java.awt.Color(58, 175, 169));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 246));
        jLabel1.setText("Last Name:");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 250, 246));
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 250, 246));
        jLabel3.setText("Birthday:");

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 250, 246));
        jLabel4.setText("Number:");

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 250, 246));
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 250, 246));
        jLabel6.setText("Email:");

        LastNameOutput.setBackground(new java.awt.Color(157, 218, 215));
        LastNameOutput.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        LastNameOutput.setForeground(new java.awt.Color(102, 102, 102));
        LastNameOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LastNameOutput.setOpaque(true);

        FirstNameOutput.setBackground(new java.awt.Color(157, 218, 215));
        FirstNameOutput.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        FirstNameOutput.setForeground(new java.awt.Color(102, 102, 102));
        FirstNameOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        FirstNameOutput.setOpaque(true);

        BirthdayOutput.setBackground(new java.awt.Color(157, 218, 215));
        BirthdayOutput.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        BirthdayOutput.setForeground(new java.awt.Color(102, 102, 102));
        BirthdayOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BirthdayOutput.setOpaque(true);

        NumberOutput.setBackground(new java.awt.Color(157, 218, 215));
        NumberOutput.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        NumberOutput.setForeground(new java.awt.Color(102, 102, 102));
        NumberOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NumberOutput.setOpaque(true);

        AddressOutput.setBackground(new java.awt.Color(157, 218, 215));
        AddressOutput.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        AddressOutput.setForeground(new java.awt.Color(102, 102, 102));
        AddressOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddressOutput.setOpaque(true);

        EmailOutput.setBackground(new java.awt.Color(157, 218, 215));
        EmailOutput.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        EmailOutput.setForeground(new java.awt.Color(102, 102, 102));
        EmailOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EmailOutput.setOpaque(true);

        DeleteEntry.setBackground(new java.awt.Color(0, 102, 102));
        DeleteEntry.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        DeleteEntry.setForeground(new java.awt.Color(255, 250, 246));
        DeleteEntry.setText("Delete");
        DeleteEntry.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DeleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEntryActionPerformed(evt);
            }
        });

        UpdateEntry.setBackground(new java.awt.Color(0, 102, 102));
        UpdateEntry.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        UpdateEntry.setForeground(new java.awt.Color(255, 250, 246));
        UpdateEntry.setText("Edit");
        UpdateEntry.setToolTipText("");
        UpdateEntry.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UpdateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(89, 89, 89))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(71, 71, 71))
                            .addComponent(FirstNameOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(107, 107, 107))
                            .addComponent(NumberOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(117, 117, 117))
                            .addComponent(EmailOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(98, 98, 98))
                            .addComponent(AddressOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BirthdayOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LastNameOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(UpdateEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumberOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirthdayOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteEntry)
                    .addComponent(UpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DeleteEntry, UpdateEntry});

        jPanel3.setBackground(new java.awt.Color(58, 175, 169));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        for (int i =0; i<CRUD_Interface.firstNameList.size();i++){
            model.addElement(CRUD_Interface.bubbleSort(CRUD_Interface.firstNameList)[i]);
        }
        jList1.setBackground(new java.awt.Color(50, 156, 151));
        jList1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 250, 246));
        jList1.setModel(model);
        jList1.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent listSelectionEvent){
                boolean adjust = listSelectionEvent.getValueIsAdjusting();
                System.out.println(", Adjusting? " + adjust);
                if (!adjust) {
                    JList list = (JList) listSelectionEvent.getSource();
                    int selections[] = list.getSelectedIndices();
                    Object selectionValues[] = list.getSelectedValues();
                    for (int i = 0, n = selections.length; i < n; i++) {
                        if (i == 0) {
                            System.out.println(" Selections: ");
                        }
                        System.out.println(selections[i] + "/" + selectionValues[i] + " ");
                        String[] Entry = CRUD_Interface.searchRow(selectionValues[i].toString(),CRUD_Interface.firstNameList);
                        LastNameOutput.setText(Entry[1]);
                        FirstNameOutput.setText(Entry[0]);
                        BirthdayOutput.setText(Entry[2]);
                        AddressOutput.setText(Entry[3]);
                        EmailOutput.setText(Entry[4]);
                        NumberOutput.setText(Entry[5]);
                    }
                }

            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel25.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 250, 246));
        jLabel25.setText("Contact List:");

        AddEntry.setBackground(new java.awt.Color(0, 102, 102));
        AddEntry.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        AddEntry.setForeground(new java.awt.Color(255, 250, 246));
        AddEntry.setText("Create");
        AddEntry.setToolTipText("");
        AddEntry.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(0, 102, 102));
        SearchButton.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 250, 246));
        SearchButton.setText("Search");
        SearchButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(AddEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void keyStrokeValidate(KeyEvent ke,JTextField InputComponent, int CharCount){
        String field = InputComponent.getText();
        if ((( ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9')&& field.length()  <= CharCount-1)
            ||(ke.getKeyChar() == '-')
            || ke.getKeyCode() == KeyEvent.VK_BACK_SPACE
            || ke.getKeyCode() == KeyEvent.VK_DELETE
            ){
            InputComponent.setEditable(true);
        } else{
            InputComponent.setEditable(false);
        }
    }
    private static boolean InputVerifier(String date,String Email,String number) {
        if (date.matches("^[0-9/]*$")&&Email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")&&number.matches("^[0-9.-]*$")){
            System.out.println("Data Passes Regex Verification");
            return true;     
        } else{
            System.out.println("Data Did not Pass Regex Verification");
            return false;
        }
    }
    public static int indexLocate(DefaultListModel<String> model, String input){
            int i;
            for (i=0;i<model.size();i++){
                //for (int j = i+1;j<model.size();j++){
                    if(model.get(i).compareTo(input) > 0){
                        //System.out.println("<0 " + model.get(i).compareTo(input));
                        break;

                    }
                //}
            }
            return i;
        }
    public static String convertToTitleCaseIteratingChars(String text) {
    if (text == null || text.isEmpty()) {
        return text;
    }

    StringBuilder converted = new StringBuilder();

    boolean convertNext = true;
    for (char ch : text.toCharArray()) {
        if (Character.isSpaceChar(ch)) {
            convertNext = true;
        } else if (convertNext) {
            ch = Character.toTitleCase(ch);
            convertNext = false;
        } else {
            ch = Character.toLowerCase(ch);
        }
        converted.append(ch);
    }

    return converted.toString();
    }
    private void AddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryActionPerformed
        AddEntryDialog.setVisible(true);  
        
    }//GEN-LAST:event_AddEntryActionPerformed
    

    private void UpdateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEntryActionPerformed
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Please select a contact to edit.");
            JOptionPane.showMessageDialog(rootPane,"Please select a contact to edit.","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            UpdateEntryDialog.setVisible(true);
            FirstNameTextField.setText(FirstNameOutput.getText());
            LastNameTextField.setText(LastNameOutput.getText());
            AddressTextField.setText(AddressOutput.getText());
            String[] DateSplices = BirthdayOutput.getText().split("/");
            BirthDayTextField.setText(DateSplices[0]);
            BirthMonthTextField.setText(DateSplices[1]);
            BirthYearTextField.setText(DateSplices[2]);
            EmailTextField.setText(EmailOutput.getText());
            NumberTextField.setText(NumberOutput.getText());
        }
        
        
    }//GEN-LAST:event_UpdateEntryActionPerformed
    private static void DeleteGUIChoice(DefaultListModel<String> model, String input ){
        try{
            int i;
            for (i=0;i<model.size();i++){
                    if(model.get(i).equals(input)){
                        model.remove(i);
                        System.out.println("GUI block removed");
                        break;
                    }
            }
        }catch(Exception err){
            System.out.println(err);
        }
        
    }
    private void DeleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEntryActionPerformed
        // TODO add your handling code here:
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Error: No Info to Delete");
            JOptionPane.showMessageDialog(rootPane,"Error: No Info to Delete","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String[] choices= {"Yes","No"};
            int response=JOptionPane.showOptionDialog(this, "Do you confirm the Deletion of These Data?", "Deletion Confirmation", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, choices, choices[0]);
            switch (response) {
                case 0 -> {
                    CRUD_Interface.deleteRow(FirstNameOutput.getText(), EmailOutput.getText());
                    DeleteGUIChoice(model,FirstNameOutput.getText());
                    System.out.println("Data Deleted");
                    FirstNameOutput.setText("");
                    LastNameOutput.setText("");
                    AddressOutput.setText("");
                    BirthdayOutput.setText("");
                    EmailOutput.setText("");
                    NumberOutput.setText("");
                    CRUD_Interface.getAllRows();
                }
                case 1 -> System.out.println("Deletion cancelled");
                default -> System.out.println("No Choice");
            }
        }
    }//GEN-LAST:event_DeleteEntryActionPerformed

    private void BirthDayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDayInputActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void BirthDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BirthDayTextFieldActionPerformed

    private void NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void AddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String NewBirthDate = BirthDayTextField.getText()+"/"+BirthMonthTextField.getText()+"/"+BirthYearTextField.getText();
        if(InputVerifier(NewBirthDate, EmailTextField.getText(),NumberTextField.getText())){
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.firstNameList, FirstNameTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.lastNameList, LastNameTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.BirthdayList, NewBirthDate);
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.numberList, NumberTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.AddressList, AddressTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.EmailList, EmailTextField.getText());
            model.removeElement(FirstNameOutput.getText());
            model.add(indexLocate(model,   convertToTitleCaseIteratingChars(FirstNameTextField.getText())),FirstNameTextField.getText());
            FirstNameOutput.setText(FirstNameTextField.getText());
            LastNameOutput.setText(LastNameTextField.getText());
            BirthdayOutput.setText(NewBirthDate);
            NumberOutput.setText(NumberTextField.getText());
            AddressOutput.setText(AddressTextField.getText());
            EmailOutput.setText(EmailTextField.getText());
            UpdateEntryDialog.dispose();
            CRUD_Interface.getAllRows();
        }else{
            JOptionPane.showMessageDialog( UpdateEntryDialog,"Error: Incorrect Data","Error",JOptionPane.ERROR_MESSAGE);
            AddEntryDialog.dispose();
        }
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UpdateEntryDialog.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddEntryBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryBackButtonActionPerformed
        // TODO add your handling code here:
        AddEntryDialog.dispose();
    }//GEN-LAST:event_AddEntryBackButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        CRUD_Interface.getAllRows();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BirthMonthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthInputActionPerformed

    private void BirthYearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthYearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthYearInputActionPerformed

    private void BirthMonthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthTextFieldActionPerformed

    private void LastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameInputActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try{
            String query = JOptionPane.showInputDialog(rootPane, "Search:");  
            if (CRUD_Interface.SearchAllFields(query)!= null){
                String[] findings = CRUD_Interface.SearchAllFields(query);
                FirstNameOutput.setText(findings[0]);
                LastNameOutput.setText(findings[1]);
                BirthdayOutput.setText(findings[2]);
                AddressOutput.setText(findings[3]);
                EmailOutput.setText(findings[4]);
                NumberOutput.setText(findings[5]);
                System.out.println("Found");
                jList1.setCellRenderer(new DefaultListCellRenderer(){
                    @Override
                    public Component getListCellRendererComponent(JList list, Object value,int index, boolean isSelected, boolean cellHasFocus) {
                        super.getListCellRendererComponent(list, value, index, isSelected,cellHasFocus);
                        String num = (String) value;
                        if (num.equals(findings[0])) {
                          setBackground(Color.lightGray);
                        }
                        return this;
                    }                
                });
            }
        }catch(ArrayIndexOutOfBoundsException err){
            JOptionPane.showMessageDialog(rootPane,"No match. Plese try again.","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("No match. Plese try again.");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhonebookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhonebookApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEntry;
    private javax.swing.JButton AddEntryBackButton;
    private javax.swing.JDialog AddEntryDialog;
    private javax.swing.JTextField AddressInput;
    private javax.swing.JLabel AddressOutput;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField BirthDayInput;
    private javax.swing.JTextField BirthDayTextField;
    private javax.swing.JTextField BirthMonthInput;
    private javax.swing.JTextField BirthMonthTextField;
    private javax.swing.JTextField BirthYearInput;
    private javax.swing.JTextField BirthYearTextField;
    private javax.swing.JLabel BirthdayOutput;
    private javax.swing.JButton DeleteEntry;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailOutput;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JLabel FirstNameOutput;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameInput;
    private javax.swing.JLabel LastNameOutput;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField NumberInput;
    private javax.swing.JLabel NumberOutput;
    private javax.swing.JTextField NumberTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JDialog SearchDialog;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton UpdateEntry;
    private javax.swing.JDialog UpdateEntryDialog;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
